imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name:        FCR_SESSION_ID
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["NbsCVBundle", "OryzoneBoilerplateBundle", "FabienCrassatCurriculumVitaeBundle", MremiContactBundle]
    filters:
        cssrewrite: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FabienCrassat Configuration
fabien_crassat_curriculum_vitae:
    path_to_cv:       "%kernel.root_dir%/../src/Nbs/Bundle/CVBundle/Resources/curriculumvitae"
    custo_default_cv: "fabien"
    template:         "NbsCVBundle:Default:index.html.twig"

# Mremi Contact Configuration
mremi_contact:
    store_data:            false
    contact_class:         Mremi\ContactBundle\Model\Contact

    form:
        type:              mremi_contact
        name:              contact_form
        validation_groups: [Default]
        subject_provider:  mremi_contact.subject_provider.noop
        captcha_type:      genemu_captcha

    email:
        mailer:            mremi_contact.mailer.twig_swift
        to:
            - {address: webmaster@crassat.com, name: Webmaster}
        template:          MremiContactBundle:Contact:email.txt.twig

a5sys_pdf:
    binary: "%kernel.root_dir%/../bin/wkhtmltopdf"
    # temp_dir: "D:/tmp"
    # encoding: "UTF-8"
    # command_options:
    #    use_exec: true
    #    escape_args: false
    #    proc_options:
    #        bypass_shell: true
    #        suppress_errors: false

netinfluence_secure_display:
    # Required, key used to encrypt data
    key: "%secret%"
    # Optional, you can customize used template here
    template: 'NetinfluenceSecureDisplayBundle::secure_display.html.twig'
