fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

netinfluence_secure_display:
    resource: "@NetinfluenceSecureDisplayBundle/Resources/config/routing.yml"

fabiencrassat_curriculumvitae:
    resource: "@FabienCrassatCurriculumVitaeBundle/Resources/config/routing.yml"

nbs_cv:
    resource: "@NbsCVBundle/Resources/config/routing.yml"
